### ISSUE TITLE
Neurons can fire multiple time steps in a row.

### ISSUE THREAD

**Issue by EvilxFish** [jeshraghian/snntorch#159]
It is possible to have neurons firing continuously using the default reset mechanism or if using RLeaky and reset to zero. The latter is due to only resetting the input but not the recurrent connections. This is undesirable behavior as it allows the neurons to essentially not be spiking neurons given the right weight values.

**Comment by jeshraghian** [comment]
Thanks for opening the issue! 

To fix this, `RLeaky` and `RSynaptic` need their reset-to-zero functions modified.

At present, only the input is being subtracted; not the recurrent inputs which causes non-zero states, and therefore, non-zero/soft resets. 

I'll try to fix this sometime in the next couple of days.

**Comment by jeshraghian** [comment]
This should be fixed in the latest push! The membrane potential for a given neuron should be zero in the time step that follows after a spike. Let me know if your case is still acting up.

**Comment by EvilxFish** [comment]
Unfortunately it still seems that the issue persists and I am able to get neurons spiking for multiple time steps in a row. To update to the latest version I ran git pull origin master, followed by python setup.py install.

**Comment by EvilxFish** [comment]
Just to finish this off, this issue has now been resolved. I believed the problem persisted as I was using:

    net[1](net[0](data))
to get the spike record (where net[1] was a spiking layer). However this does **not** work as intended and the correct way to get the spike record is to run:

    net(data)
    net[1].spk
if your spiking layer is a hidden layer. Thank you for the fix!
